import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { DOCUMENT_TYPE_OPTIONS } from "@/lib/crm";
import type { FacesheetData } from "@shared/referralDocuments";
import { Building2, ContactRound, CreditCard, FileHeart, Hospital, Stethoscope } from "lucide-react";

function Field({ label, value, onChange, className = "" }: { label: string; value: string; onChange: (value: string) => void; className?: string }) {
  return <div className={`space-y-2 ${className}`}><Label>{label}</Label><Input value={value} onChange={event => onChange(event.target.value)} className="h-10 border-slate-200 bg-white" /></div>;
}

function Area({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) {
  return <div className="space-y-2"><Label>{label}</Label><Textarea value={value} onChange={event => onChange(event.target.value)} rows={3} className="border-slate-200 bg-white" /></div>;
}

export function FacesheetReview({ value, onChange, documentCategory, onDocumentCategoryChange }: {
  value: FacesheetData;
  onChange: (value: FacesheetData) => void;
  documentCategory: string;
  onDocumentCategoryChange: (value: string) => void;
}) {
  const set = (key: keyof FacesheetData, next: string | string[]) => onChange({ ...value, [key]: next });
  return <section className="rounded-2xl border border-cyan-100 bg-cyan-50/45 p-5 sm:p-6">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-cyan-800">Hospital Facesheet review</p><h3 className="mt-2 text-lg font-semibold text-slate-950">Verify encounter, contacts, insurance, and clinical details</h3><p className="mt-1 text-sm leading-6 text-slate-600">The standard and extended values identify the document layout only. Patient, contact, guarantor, provider, and facility information remain separate.</p></div><div className="w-full space-y-2 sm:w-64"><Label>Detected document type</Label><Select value={documentCategory} onValueChange={onDocumentCategoryChange}><SelectTrigger className="bg-white"><SelectValue /></SelectTrigger><SelectContent>{DOCUMENT_TYPE_OPTIONS.map(([key, label]) => <SelectItem key={key} value={key}>{label}</SelectItem>)}</SelectContent></Select></div></div>

    <div className="mt-6 space-y-6">
      <div><div className="mb-4 flex items-center gap-2"><Hospital className="h-4 w-4 text-cyan-800" /><h4 className="font-semibold">Hospital encounter</h4></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="Facility" value={value.facilityName} onChange={next => set("facilityName", next)} /><Field label="Facility location" value={value.facilityLocation} onChange={next => set("facilityLocation", next)} /><Field label="Encounter type" value={value.encounterType} onChange={next => set("encounterType", next)} /><Field label="Financial / account number" value={value.financialAccountNumber} onChange={next => set("financialAccountNumber", next)} /><Field label="Arrival date" value={value.arrivalDate} onChange={next => set("arrivalDate", next)} /><Field label="Arrival time" value={value.arrivalTime} onChange={next => set("arrivalTime", next)} /><Field label="Admit date" value={value.admitDate} onChange={next => set("admitDate", next)} /><Field label="Admit time" value={value.admitTime} onChange={next => set("admitTime", next)} /><Field label="Discharge date" value={value.dischargeDate} onChange={next => set("dischargeDate", next)} /><Field label="Discharge time" value={value.dischargeTime} onChange={next => set("dischargeTime", next)} /><Field label="Room / bed" value={value.roomBed} onChange={next => set("roomBed", next)} /><Field label="Length of stay" value={value.lengthOfStay} onChange={next => set("lengthOfStay", next)} /></div></div>

      <div className="border-t border-cyan-100 pt-6"><div className="mb-4 flex items-center gap-2"><ContactRound className="h-4 w-4 text-cyan-800" /><h4 className="font-semibold">Patient demographics and contact</h4></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="Patient language" value={value.patientLanguage} onChange={next => set("patientLanguage", next)} /><Field label="Race" value={value.race} onChange={next => set("race", next)} /><Field label="Religion" value={value.religion} onChange={next => set("religion", next)} /><Field label="Ethnic group" value={value.ethnicGroup} onChange={next => set("ethnicGroup", next)} /><Field label="Country of birth" value={value.countryOfBirth} onChange={next => set("countryOfBirth", next)} /><Field label="Marital status" value={value.maritalStatus} onChange={next => set("maritalStatus", next)} /><Field label="Occupation" value={value.occupation} onChange={next => set("occupation", next)} /><Field label="Cell phone" value={value.cellPhone} onChange={next => set("cellPhone", next)} /><Field label="Alternate phone" value={value.alternatePhone} onChange={next => set("alternatePhone", next)} /></div></div>

      <div className="grid gap-6 border-t border-cyan-100 pt-6 lg:grid-cols-3"><ContactSection title="Next of kin" name={value.nextOfKinName} relationship={value.nextOfKinRelationship} phone={value.nextOfKinPhone} setName={next => set("nextOfKinName", next)} setRelationship={next => set("nextOfKinRelationship", next)} setPhone={next => set("nextOfKinPhone", next)} /><ContactSection title="Emergency contact" name={value.emergencyContactName} relationship={value.emergencyContactRelationship} phone={value.emergencyContactPhone} setName={next => set("emergencyContactName", next)} setRelationship={next => set("emergencyContactRelationship", next)} setPhone={next => set("emergencyContactPhone", next)} /><div><div className="mb-4 flex items-center gap-2"><Building2 className="h-4 w-4 text-cyan-800" /><h4 className="font-semibold">Guarantor</h4></div><div className="space-y-4"><Field label="Name" value={value.guarantorName} onChange={next => set("guarantorName", next)} /><Field label="Relationship" value={value.guarantorRelationship} onChange={next => set("guarantorRelationship", next)} /><Field label="Phone" value={value.guarantorPhone} onChange={next => set("guarantorPhone", next)} /><Field label="Address" value={value.guarantorAddress} onChange={next => set("guarantorAddress", next)} /></div></div></div>

      <div className="grid gap-6 border-t border-cyan-100 pt-6 lg:grid-cols-2"><InsuranceSection title="Primary insurance" carrier={value.primaryInsuranceCarrier} plan={value.primaryInsurancePlan} memberId={value.primaryMemberId} groupNumber={value.primaryGroupNumber} authorizationNumber={value.primaryAuthorizationNumber} setCarrier={next => set("primaryInsuranceCarrier", next)} setPlan={next => set("primaryInsurancePlan", next)} setMemberId={next => set("primaryMemberId", next)} setGroupNumber={next => set("primaryGroupNumber", next)} setAuthorizationNumber={next => set("primaryAuthorizationNumber", next)} /><InsuranceSection title="Secondary insurance" carrier={value.secondaryInsuranceCarrier} plan={value.secondaryInsurancePlan} memberId={value.secondaryMemberId} groupNumber={value.secondaryGroupNumber} setCarrier={next => set("secondaryInsuranceCarrier", next)} setPlan={next => set("secondaryInsurancePlan", next)} setMemberId={next => set("secondaryMemberId", next)} setGroupNumber={next => set("secondaryGroupNumber", next)} /></div>

      <div className="border-t border-cyan-100 pt-6"><div className="mb-4 flex items-center gap-2"><Stethoscope className="h-4 w-4 text-cyan-800" /><h4 className="font-semibold">Care team</h4></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="Attending physician" value={value.attendingPhysician} onChange={next => set("attendingPhysician", next)} /><Field label="Emergency physician" value={value.emergencyPhysician} onChange={next => set("emergencyPhysician", next)} /><Field label="Primary care physician" value={value.primaryCarePhysician} onChange={next => set("primaryCarePhysician", next)} /><Field label="Referring / transferring facility" value={value.referringFacility} onChange={next => set("referringFacility", next)} /><Field label="Hospital service" value={value.hospitalService} onChange={next => set("hospitalService", next)} /></div></div>

      <div className="border-t border-cyan-100 pt-6"><div className="mb-4 flex items-center gap-2"><FileHeart className="h-4 w-4 text-cyan-800" /><h4 className="font-semibold">Clinical details</h4></div><div className="grid gap-4 lg:grid-cols-2"><Area label="Admit diagnosis" value={value.admitDiagnosis} onChange={next => set("admitDiagnosis", next)} /><Area label="Visit reason" value={value.visitReason} onChange={next => set("visitReason", next)} /><Area label="Principal diagnosis" value={value.principalDiagnosis} onChange={next => set("principalDiagnosis", next)} /><Area label="Other diagnoses" value={value.otherDiagnoses} onChange={next => set("otherDiagnoses", next)} /><Area label="Principal procedure" value={value.principalProcedure} onChange={next => set("principalProcedure", next)} /><Area label="Other procedures" value={value.otherProcedures} onChange={next => set("otherProcedures", next)} /><Field label="ICD codes" value={value.icdCodes.join(", ")} onChange={next => set("icdCodes", next.split(",").map(item => item.trim()).filter(Boolean))} className="lg:col-span-2" /></div></div>
    </div>
  </section>;
}

function ContactSection({ title, name, relationship, phone, setName, setRelationship, setPhone }: { title: string; name: string; relationship: string; phone: string; setName: (value: string) => void; setRelationship: (value: string) => void; setPhone: (value: string) => void }) {
  return <div><div className="mb-4 flex items-center gap-2"><ContactRound className="h-4 w-4 text-cyan-800" /><h4 className="font-semibold">{title}</h4></div><div className="space-y-4"><Field label="Name" value={name} onChange={setName} /><Field label="Relationship" value={relationship} onChange={setRelationship} /><Field label="Phone" value={phone} onChange={setPhone} /></div></div>;
}

function InsuranceSection({ title, carrier, plan, memberId, groupNumber, authorizationNumber, setCarrier, setPlan, setMemberId, setGroupNumber, setAuthorizationNumber }: { title: string; carrier: string; plan: string; memberId: string; groupNumber: string; authorizationNumber?: string; setCarrier: (value: string) => void; setPlan: (value: string) => void; setMemberId: (value: string) => void; setGroupNumber: (value: string) => void; setAuthorizationNumber?: (value: string) => void }) {
  return <div><div className="mb-4 flex items-center gap-2"><CreditCard className="h-4 w-4 text-cyan-800" /><h4 className="font-semibold">{title}</h4></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Carrier" value={carrier} onChange={setCarrier} /><Field label="Plan" value={plan} onChange={setPlan} /><Field label="Member / policy ID" value={memberId} onChange={setMemberId} /><Field label="Group number" value={groupNumber} onChange={setGroupNumber} />{setAuthorizationNumber && <Field label="Authorization number" value={authorizationNumber ?? ""} onChange={setAuthorizationNumber} className="sm:col-span-2" />}</div></div>;
}
